-- +goose Up
-- +goose StatementBegin
CREATE TABLE digest (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INT NOT NULL ,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    published_at TIMESTAMP NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS sources;
-- +goose StatementEnd