-- +goose Up
-- +goose StatementBegin
CREATE TABLE sources (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    meta JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS sources;
-- +goose StatementEnd
