-- +goose Up
-- +goose StatementBegin
CREATE TABLE digest (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id INT NOT NULL,
    digest_id INT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    genre TEXT NOT NULL,
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS digest;
-- +goose StatementEnd